{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import cv2\n",
    "import torch\n",
    "from IPython.display import Image\n",
    "from random import choice\n",
    "import shutil\n",
    "import glob\n",
    "import numpy as np\n",
    "import shutil\n",
    "import re\n",
    "from collections import defaultdict\n",
    "from PIL import Image\n",
    "import subprocess\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "###path\n",
    "base_path = \"your path\"\n",
    "\n",
    "all_video_input = f\"{base_path}/all_video\"\n",
    "#one_video_input = f\"{all_video_input}/salam1.mp4\"\n",
    "video_folder = f\"{base_path}/1_video\"\n",
    "video_in_video_folder = f\"{video_folder}/video.mp4\"\n",
    "\n",
    "convert_video_to_images_folder = f\"{base_path}/2_convert_video_to_images\"\n",
    "square_images_folder = f\"{base_path}/3_square_images\"\n",
    "resized_images_folder = f\"{base_path}/4_resized_images\"\n",
    "data_end = f\"{base_path}/data\"\n",
    "\n",
    "yolo_folder = f\"{base_path}/yolov5\"\n",
    "detect_folder = f\"{yolo_folder}/runs/detect\"\n",
    "labels_folder = f\"{detect_folder}/exp/labels\"\n",
    "yolo_weights_path = f\"{yolo_folder}/runs/train/weights/best.pt\"\n",
    "\n",
    "model_path = f\"{base_path}/cnn_rnn_model.h5\"\n",
    "\n",
    "dataset_end = f\"{base_path}/dataset\"\n",
    "\n",
    "#name class\n",
    "name_class = \"name your class\"\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "paths = [\n",
    "    video_folder,\n",
    "    convert_video_to_images_folder,\n",
    "    square_images_folder,\n",
    "    resized_images_folder,\n",
    "    yolo_weights_path,\n",
    "    dataset_end\n",
    "]\n",
    "\n",
    "# make folders\n",
    "for path in paths:\n",
    "    try:\n",
    "        os.makedirs(path)\n",
    "        print(f\"Folder created: {path}\")\n",
    "    except FileExistsError:\n",
    "        print(f\"Folder already exists: {path}\")\n",
    " \n",
    "\n",
    "\n",
    "\n",
    "### 1_ Deleted all files\n",
    "\n",
    "\n",
    "\n",
    "def delete_files_and_folders(pathsـdelete_files):\n",
    "    for folder_path in pathsـdelete_files:\n",
    "        items = glob.glob(os.path.join(folder_path, \"*\"))\n",
    "\n",
    "        for item in items:\n",
    "            try:\n",
    "                if os.path.isfile(item) or os.path.islink(item):\n",
    "                    os.remove(item)  \n",
    "            \n",
    "                elif os.path.isdir(item):\n",
    "                    shutil.rmtree(item)  \n",
    "                    print(f\"Deleted folder: {item}\")\n",
    "            except Exception as e:\n",
    "                print(f\"Error deleting {item}: {e}\")\n",
    "\n",
    "\n",
    "### 2_ cut up and down video and change name video\n",
    "\n",
    "def crop_video(video_path_change_name_video, save_path_change_name_video):\n",
    "\n",
    "    video_capture = cv2.VideoCapture(video_path_change_name_video)\n",
    "\n",
    "    width = int(video_capture.get(cv2.CAP_PROP_FRAME_WIDTH))\n",
    "    height = int(video_capture.get(cv2.CAP_PROP_FRAME_HEIGHT))\n",
    "\n",
    "    min_size = min(width, height)\n",
    "    start_x = (width - min_size) // 2\n",
    "    start_y = (height - min_size) // 2\n",
    "\n",
    "    crop_region = (start_x, start_y, min_size, min_size)\n",
    "\n",
    "    fourcc = cv2.VideoWriter_fourcc(*'mp4v') \n",
    "    video_writer = cv2.VideoWriter(save_path_change_name_video, fourcc, 30, (min_size, min_size))\n",
    "\n",
    "    while True:\n",
    "        ret, frame = video_capture.read()\n",
    "        if not ret:\n",
    "            break\n",
    "\n",
    "        cropped_frame = frame[start_y:start_y+min_size, start_x:start_x+min_size]\n",
    "\n",
    "\n",
    "        video_writer.write(cropped_frame)\n",
    "\n",
    "\n",
    "    video_capture.release()\n",
    "    video_writer.release()\n",
    "    cv2.destroyAllWindows()\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "### 3_ ran yolo model\n",
    "\n",
    "def run_yolov5_detection(video_source, weights_path, conf_threshold=0.4, vid_stride=1):\n",
    "    \"\"\"\n",
    "    Runs YOLOv5 object detection on a video source.\n",
    "\n",
    "    Parameters:\n",
    "        video_source (str): Path to the video file or directory containing images.\n",
    "        weights_path (str): Path to the YOLOv5 weights file.\n",
    "        conf_threshold (float, optional): Confidence threshold for detection. Defaults to 0.4.\n",
    "        vid_stride (int, optional): Frame stride for video processing. Defaults to 1.\n",
    "    \"\"\"\n",
    "    \n",
    "    # Ensure the directory exists\n",
    "    if not os.path.exists(yolo_folder):\n",
    "        raise FileNotFoundError(f\"Directory {yolo_folder} does not exist\")\n",
    "    \n",
    "    # Construct the command with absolute paths\n",
    "    detect_script = os.path.join(yolo_folder, 'detect.py')\n",
    "    command = [\n",
    "        'python', detect_script,\n",
    "        '--source', video_source,\n",
    "        '--weights', weights_path,\n",
    "        '--save-txt',\n",
    "        '--vid-stride', str(vid_stride),\n",
    "        '--conf-thres', str(conf_threshold)\n",
    "    ]\n",
    "    \n",
    "    # Run the YOLOv5 detection script and capture output\n",
    "    try:\n",
    "        result = subprocess.run(command, check=True, capture_output=True, text=True)\n",
    "        print(\"Command Output:\", result.stdout)\n",
    "        print(\"Command Error:\", result.stderr)\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        print(\"Error executing command:\")\n",
    "        print(e.output)\n",
    "        print(e.stderr)\n",
    "        raise\n",
    "\n",
    "\n",
    "\n",
    "###4_ extract frames from video\n",
    "def convert_video_to_images(video_path, output_folder):\n",
    "    base_name = os.path.basename(video_path).split('.')[0]\n",
    "    \n",
    "    vidcap = cv2.VideoCapture(video_path)\n",
    "    success, image = vidcap.read()\n",
    "    count = 0\n",
    "    frame_interval = 1 \n",
    "\n",
    "    if not os.path.exists(output_folder):\n",
    "        os.makedirs(output_folder)\n",
    "\n",
    "    while success:\n",
    "        if count % frame_interval == 0:\n",
    "            image_path = os.path.join(output_folder, f\"{base_name}_{count // frame_interval + 1}.jpg\")\n",
    "            cv2.imwrite(image_path, image) \n",
    "        success, image = vidcap.read()\n",
    "        count += 1\n",
    "\n",
    "    print(f\"{count // frame_interval} frames extracted.\")\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "###5_ Convert photos to black and white\n",
    "\n",
    "def convert_photos_to_grayscale(input_folder):\n",
    "    \"\"\"\n",
    "    Converts photos in the input folder to grayscale and saves them in the output folder.\n",
    "\n",
    "    Args:\n",
    "        input_folder (str): The path to the folder containing the images.\n",
    "        output_folder (str): The path to the folder where the grayscale images will be saved.\n",
    "    \"\"\"\n",
    "    if not os.path.exists(input_folder):\n",
    "        os.makedirs(input_folder)\n",
    "\n",
    "    for filename in os.listdir(input_folder):\n",
    "        if filename.endswith(\".jpg\"):\n",
    "            input_path = os.path.join(input_folder, filename)\n",
    "            \n",
    "            img = cv2.imread(input_path)\n",
    "            \n",
    "            gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n",
    "            \n",
    "\n",
    "            output_path = os.path.join(input_folder, filename)\n",
    "\n",
    "            cv2.imwrite(output_path, gray_img)\n",
    "            \n",
    "            print(f\"Converted {filename} to grayscale and saved to {output_path}\")\n",
    "\n",
    "    print(\"Conversion completed.\")\n",
    "\n",
    "\n",
    "### 6_ add 1,2,3 to ferst file .txt with Right hand and left hand detection\n",
    "\n",
    "def add_number_to_ferst_file(folder_path_labels):\n",
    "    file_pattern = os.path.join(folder_path_labels , \"*_1.txt\")\n",
    "    files = glob.glob(file_pattern)\n",
    "\n",
    "    if files:\n",
    "        file_path = files[0]\n",
    "        with open(file_path, 'r+') as f:\n",
    "            lines = f.readlines()\n",
    "        \n",
    "        hands = []\n",
    "        others = []\n",
    "        for line in lines:\n",
    "            if line.startswith(\"1\"):\n",
    "                hands.append(line.strip())\n",
    "            else:\n",
    "                others.append(line.strip())\n",
    "        \n",
    "        hands_sorted = sorted(hands, key=lambda x: float(x.split()[1]))\n",
    "        \n",
    "        right_hand = \"\"\n",
    "        left_hand = \"\"\n",
    "\n",
    "        if len(hands_sorted) >= 1:\n",
    "            right_hand = hands_sorted[0] + \" 1\"\n",
    "        if len(hands_sorted) >= 2:\n",
    "            left_hand = hands_sorted[1] + \" 2\"\n",
    "\n",
    "        others = [coord + \" 3\" for coord in others]\n",
    "\n",
    "        result = []\n",
    "        if right_hand:\n",
    "            result.append(right_hand)\n",
    "        if left_hand:\n",
    "            result.append(left_hand)\n",
    "        result.extend(others)\n",
    "\n",
    "        with open(file_path, 'w') as f:\n",
    "            for line in result:\n",
    "                f.write(line + \"\\n\")\n",
    "\n",
    "        print(f\"file '{file_path}' Successfully updated.\")\n",
    "    else:\n",
    "        print(\"No file with extension _1.txt was found in the desired path.\")\n",
    "\n",
    "\n",
    "\n",
    "######7_ Prepare text file for cut image\n",
    "\n",
    "def Prepare_text_file_for_cut_image(directory_path_labels_folder):\n",
    "\n",
    "    def extract_first_digit_after_decimal(line):\n",
    "        parts = line.strip().split()\n",
    "        first_digits_after_decimal = []\n",
    "        for part in parts[1:5]:\n",
    "            if '.' in part:\n",
    "                fraction_part = part.split('.')[1]\n",
    "                if len(fraction_part) > 0:\n",
    "                    first_digits_after_decimal.append(int(fraction_part[0]))\n",
    "                else:\n",
    "                    first_digits_after_decimal.append(0)\n",
    "            else:\n",
    "                first_digits_after_decimal.append(0)\n",
    "        return first_digits_after_decimal\n",
    "\n",
    "    def extract_second_digit_after_decimal(line):\n",
    "        parts = line.strip().split()\n",
    "        second_digits_after_decimal = []\n",
    "        for part in parts[1:5]:\n",
    "            if '.' in part:\n",
    "                fraction_part = part.split('.')[1]\n",
    "                if len(fraction_part) > 1:\n",
    "                    second_digits_after_decimal.append(int(fraction_part[1]))\n",
    "                else:\n",
    "                    second_digits_after_decimal.append(0)\n",
    "            else:\n",
    "                second_digits_after_decimal.append(0)\n",
    "        return second_digits_after_decimal\n",
    "\n",
    "    def count_matching_digits(list1, list2):\n",
    "        return sum(1 for a, b in zip(list1, list2) if a == b)\n",
    "\n",
    "    def read_file(file_path):\n",
    "        with open(file_path, 'r') as file:\n",
    "            lines = file.readlines()\n",
    "        return [list(map(float, line.strip().split())) for line in lines]\n",
    "\n",
    "    def write_file(file_path, lines):\n",
    "        with open(file_path, 'w') as file:\n",
    "            for line in lines:\n",
    "                formatted_line = ' '.join([f\"{int(num)}\" if num.is_integer() else f\"{num}\" for num in line])\n",
    "                file.write(formatted_line + '\\n')\n",
    "\n",
    "    def find_lines_with_sixth_element(lines, value):\n",
    "        return [line for line in lines if len(line) > 5 and line[5] == value]\n",
    "\n",
    "    def predict_next_coordinate(prev1, prev2):\n",
    "        diff = np.array(prev2) - np.array(prev1)\n",
    "        predicted = np.array(prev2) + diff\n",
    "        return predicted\n",
    "\n",
    "    def select_best_coordinate(predicted, candidates):\n",
    "        best_candidate = None\n",
    "        best_distance = float('inf')\n",
    "        \n",
    "        for candidate in candidates:\n",
    "            candidate = np.array(candidate)\n",
    "            distance = np.linalg.norm(candidate - predicted)\n",
    "            \n",
    "            if distance < best_distance:\n",
    "                best_distance = distance\n",
    "                best_candidate = candidate\n",
    "        \n",
    "        return best_candidate\n",
    "\n",
    "    def process_files(file_path1, file_path2):\n",
    "        with open(file_path1, 'r') as file1, open(file_path2, 'r') as file2:\n",
    "            lines1 = file1.readlines()\n",
    "            lines2 = file2.readlines()\n",
    "\n",
    "        first_digits_list1 = [extract_first_digit_after_decimal(line) for line in lines1]\n",
    "        second_digits_list1 = [extract_second_digit_after_decimal(line) for line in lines1]\n",
    "\n",
    "        with open(file_path2, 'w') as file2:\n",
    "            for line2 in lines2:\n",
    "                first_digits2 = extract_first_digit_after_decimal(line2)\n",
    "                second_digits2 = extract_second_digit_after_decimal(line2)\n",
    "                matched_indices = []\n",
    "                matched = False\n",
    "\n",
    "                for i, first_digits1 in enumerate(first_digits_list1):\n",
    "                    if first_digits1 == first_digits2:\n",
    "                        matched_indices.append(i)\n",
    "\n",
    "                if len(matched_indices) == 1:\n",
    "                    parts = line2.strip().split()\n",
    "                    matched_line_parts = lines1[matched_indices[0]].strip().split()\n",
    "                    if len(matched_line_parts) > 5:\n",
    "                        parts.append(matched_line_parts[5])\n",
    "                    else:\n",
    "                        parts.append('')  # Leave the 6th number empty\n",
    "                    file2.write(' '.join(parts) + '\\n')\n",
    "                    matched = True\n",
    "                elif len(matched_indices) > 1:\n",
    "                    for i in matched_indices:\n",
    "                        if second_digits_list1[i] == second_digits2:\n",
    "                            parts = line2.strip().split()\n",
    "                            matched_line_parts = lines1[i].strip().split()\n",
    "                            if len(matched_line_parts) > 5:\n",
    "                                parts.append(matched_line_parts[5])\n",
    "                            else:\n",
    "                                parts.append('')  # Leave the 6th number empty\n",
    "                            file2.write(' '.join(parts) + '\\n')\n",
    "                            matched = True\n",
    "                            break\n",
    "\n",
    "                if not matched:\n",
    "                    for i, first_digits1 in enumerate(first_digits_list1):\n",
    "                        if count_matching_digits(first_digits1, first_digits2) >= 3:\n",
    "                            parts = line2.strip().split()\n",
    "                            matched_line_parts = lines1[i].strip().split()\n",
    "                            if len(matched_line_parts) > 5:\n",
    "                                parts.append(matched_line_parts[5])\n",
    "                            else:\n",
    "                                parts.append('')  # Leave the 6th number empty\n",
    "                            file2.write(' '.join(parts) + '\\n')\n",
    "                            matched = True\n",
    "                            break\n",
    "\n",
    "                if not matched:\n",
    "                    parts = line2.strip().split()\n",
    "                    parts.append('')  # Leave the 6th number empty\n",
    "                    file2.write(' '.join(parts) + '\\n')\n",
    "                    \n",
    "        file1_lines = read_file(file_path1)\n",
    "        file2_lines = read_file(file_path2)\n",
    "        \n",
    "        missing_values = [val for val in [1, 2, 3] if val not in [line[5] for line in file2_lines if len(line) > 5]]\n",
    "        \n",
    "        if missing_values:\n",
    "            missing_value = missing_values[0]  \n",
    "            \n",
    "            \n",
    "            file1_lines_with_missing = find_lines_with_sixth_element(file1_lines, missing_value)\n",
    "            \n",
    "            if file1_lines_with_missing:\n",
    "                \n",
    "                prev1 = file1_lines_with_missing[0][1:5]  \n",
    "                prev2 = file1_lines_with_missing[1][1:5] if len(file1_lines_with_missing) > 1 else prev1 \n",
    "                \n",
    "            \n",
    "                candidates = [line for line in file2_lines if len(line) <= 5 or (line[5] != 1 and line[5] != 2 and line[5] != 3)]\n",
    "                candidate_coords = [line[1:5] for line in candidates]\n",
    "                \n",
    "                if candidate_coords:\n",
    "                    \n",
    "                    predicted = predict_next_coordinate(prev1, prev2)\n",
    "                    \n",
    "                    \n",
    "                    best_coordinate = select_best_coordinate(predicted, candidate_coords)\n",
    "                    \n",
    "                    print(f\"best{missing_value}:\", best_coordinate)\n",
    "                    \n",
    "                    \n",
    "                    for line in candidates:\n",
    "                        if line[1:5] == best_coordinate.tolist():\n",
    "                            line.append(float(missing_value))\n",
    "                    \n",
    "                    \n",
    "                    write_file(file_path2, file2_lines)\n",
    "                else:\n",
    "                    print(\"There is no line without the sixth number or with the sixth number 1, 2, 3 in the second file.\")\n",
    "            else:\n",
    "                print(f\"No lines with numbers{missing_value} It is not present in the sixth position in the first file.\")\n",
    "        else:\n",
    "            print(\"All numbers 1, 2 and 3 are in the sixth position of the second file.\")\n",
    "\n",
    "    def process_files_in_directory(directory):\n",
    "        file_names = os.listdir(directory)\n",
    "        file_names = [f for f in file_names if f.endswith('.txt')]\n",
    "        file_names.sort(key=lambda x: int(x.split('_')[1].split('.')[0]))\n",
    "\n",
    "        for i in range(len(file_names) - 1):\n",
    "            file_path1 = os.path.join(directory, file_names[i])\n",
    "            file_path2 = os.path.join(directory, file_names[i + 1])\n",
    "            process_files(file_path1, file_path2)\n",
    "\n",
    "    directory_path = directory_path_labels_folder\n",
    "    process_files_in_directory(directory_path)\n",
    "\n",
    "\n",
    "\n",
    "###8_ Deleted lines in files that haven't six number\n",
    "def Deleted_lines_in_files_that_haven_not_six_number(directory_path_labels_folder):\n",
    "\n",
    "    def read_file(file_path):\n",
    "        with open(file_path, 'r') as file:\n",
    "            lines = file.readlines()\n",
    "        return lines\n",
    "\n",
    "    def write_file(file_path, lines):\n",
    "        with open(file_path, 'w') as file:\n",
    "            for line in lines:\n",
    "                file.write(line)\n",
    "\n",
    "    def remove_lines_without_sixth_number(file_path):\n",
    "        lines = read_file(file_path)\n",
    "        filtered_lines = [line for line in lines if len(line.strip().split()) > 5]\n",
    "        write_file(file_path, filtered_lines)\n",
    "\n",
    "    def process_files_in_directory(directory):\n",
    "        file_names = os.listdir(directory)\n",
    "        file_names = [f for f in file_names if f.endswith('.txt')]\n",
    "\n",
    "        for file_name in file_names:\n",
    "            file_path = os.path.join(directory, file_name)\n",
    "            remove_lines_without_sixth_number(file_path)\n",
    "\n",
    "    directory_path = directory_path_labels_folder\n",
    "    process_files_in_directory(directory_path)\n",
    "\n",
    "\n",
    "\n",
    "###9_ Deleted file and image to 30\n",
    "def Deleted_file_and_image(labels_directory, images_directory):\n",
    "    label_files_before = set([f for f in os.listdir(labels_directory) if f.endswith('.txt')])\n",
    "\n",
    "    def get_file_number(filename):\n",
    "        return int(filename.split('_')[1].split('.')[0])\n",
    "\n",
    "    label_files_before = sorted(label_files_before, key=get_file_number)\n",
    "\n",
    "    def reduce_files_uniformly(files, target_count):\n",
    "        total_files = len(files)\n",
    "        if total_files <= target_count:\n",
    "            return files\n",
    "        \n",
    "        step = total_files / (total_files - target_count)\n",
    "        indices_to_remove = [int(i * step) for i in range(total_files - target_count)]\n",
    "        \n",
    "        for index in sorted(indices_to_remove, reverse=True):\n",
    "            os.remove(os.path.join(labels_directory, files[index]))\n",
    "        \n",
    "        remaining_files = [f for f in os.listdir(labels_directory) if f.endswith('.txt')]\n",
    "        remaining_files.sort(key=get_file_number)\n",
    "        return remaining_files\n",
    "\n",
    "    remaining_label_files = reduce_files_uniformly(label_files_before, 30)\n",
    "\n",
    "    deleted_label_files = set(label_files_before) - set(remaining_label_files)\n",
    "\n",
    "    for label_file in deleted_label_files:\n",
    "        image_file = label_file.replace('.txt', '.jpg')\n",
    "        image_path = os.path.join(images_directory, image_file)\n",
    "        if os.path.exists(image_path):\n",
    "            os.remove(image_path)\n",
    "\n",
    "    remaining_image_files = [f for f in os.listdir(images_directory) if f.endswith('.jpg')]\n",
    "    print(f\"Number of text files remaining in labels: {len(remaining_label_files)}\")\n",
    "    print(f\"Number of image files remaining in images: {len(remaining_image_files)}\")\n",
    "\n",
    "    def rename_files(directory, extension):\n",
    "        files = [f for f in os.listdir(directory) if f.endswith(extension)]\n",
    "        \n",
    "        files.sort(key=lambda f: int(re.search(r'_(\\d+)', f).group(1)))\n",
    "        \n",
    "        for i, filename in enumerate(files, start=1):\n",
    "            new_filename = re.sub(r'_\\d+', f'_{i}', filename)\n",
    "            os.rename(os.path.join(directory, filename), os.path.join(directory, new_filename))\n",
    "\n",
    "    rename_files(labels_directory, '.txt')\n",
    "\n",
    "    rename_files(images_directory, '.jpg')\n",
    "    rename_files(images_directory, '.png')\n",
    "    rename_files(images_directory, '.jpeg')\n",
    "\n",
    "\n",
    "###10_ cut image by text file\n",
    "\n",
    "def cut_image_by_text_file(labels_folder_path, images_folder_path, save_folder):\n",
    "    def convert_to_square(file_path):\n",
    "        with open(file_path, 'r') as file:\n",
    "            lines = file.readlines()\n",
    "            modified_lines = []\n",
    "            for line in lines:\n",
    "                label, x_center, y_center, width, height, additional_number = map(float, line.split())\n",
    "                \n",
    "                max_size = max(width, height)\n",
    "                \n",
    "                x1 = max(x_center - max_size / 2, 0)\n",
    "                y1 = max(y_center - max_size / 2, 0)\n",
    "                x2 = x1 + abs(max_size)\n",
    "                y2 = y1 + abs(max_size)\n",
    "                \n",
    "                modified_lines.append(f\"{int(label)} {x1} {y1} {x2} {y2} {int(additional_number)}\\n\")\n",
    "            \n",
    "            return modified_lines\n",
    "\n",
    "    def crop_and_save_squares(image_path, coordinates, save_folder):\n",
    "        image = cv2.imread(image_path)\n",
    "        image_name = os.path.splitext(os.path.basename(image_path))[0]\n",
    "\n",
    "        for i, (label, (x1, y1), (x2, y2), additional_number) in enumerate(coordinates):\n",
    "            x1_pixel = int(x1 * image.shape[1])\n",
    "            y1_pixel = int(y1 * image.shape[0])\n",
    "            x2_pixel = int(x2 * image.shape[1])\n",
    "            y2_pixel = int(y2 * image.shape[0])\n",
    "\n",
    "            cropped_image = image[y1_pixel:y2_pixel, x1_pixel:x2_pixel]\n",
    "\n",
    "            cropped_save_path = os.path.join(save_folder, f\"{image_name}_{additional_number}_{label}.jpg\")\n",
    "            cv2.imwrite(cropped_save_path, cropped_image)\n",
    "\n",
    "\n",
    "    os.makedirs(save_folder, exist_ok=True)\n",
    "\n",
    "    file_list = os.listdir(labels_folder_path)\n",
    "\n",
    "    for file_name in file_list:\n",
    "        if file_name.endswith(\".txt\"): \n",
    "            text_file_path = os.path.join(labels_folder_path, file_name)\n",
    "            \n",
    "            modified_lines = convert_to_square(text_file_path)\n",
    "            \n",
    "            coordinates = []\n",
    "            for line in modified_lines:\n",
    "                label, x1, y1, x2, y2, additional_number = map(float, line.split())\n",
    "                coordinates.append((int(label), (x1, y1), (x2, y2), int(additional_number)))\n",
    "            \n",
    "            image_file_name = os.path.splitext(file_name)[0] + \".jpg\"\n",
    "            image_path = os.path.join(images_folder_path, image_file_name)\n",
    "            if os.path.exists(image_path):\n",
    "\n",
    "                crop_and_save_squares(image_path, coordinates, save_folder)\n",
    "            else:\n",
    "                print(f\"{file_name} not found.\")\n",
    "\n",
    "\n",
    "###11_ change Dimensions to 128 * 128\n",
    "\n",
    "def resize_images(input_folder_square_images_Dimensions, output_folder_resized_images_Dimensions, size):\n",
    "    if not os.path.exists(output_folder_resized_images_Dimensions):\n",
    "        os.makedirs(output_folder_resized_images_Dimensions)\n",
    "\n",
    "    for filename in os.listdir(input_folder_square_images_Dimensions):\n",
    "        if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.tiff')):\n",
    "            img_path = os.path.join(input_folder_square_images_Dimensions, filename)\n",
    "            image = cv2.imread(img_path)\n",
    "            if image is not None:\n",
    "                resized_image = cv2.resize(image, size)\n",
    "                \n",
    "                output_path = os.path.join(output_folder_resized_images_Dimensions, filename)\n",
    "                \n",
    "                cv2.imwrite(output_path, resized_image)\n",
    "                print(f\"Resized and saved: {filename}\")\n",
    "            else:\n",
    "                print(f\"Failed to read: {filename}\")\n",
    "\n",
    "\n",
    "###12_ mix 3 image to one with LDA\n",
    "\n",
    "def mix_image_with_LDA(input_dir, output_base_dir, weights):\n",
    "    image_groups = defaultdict(list)\n",
    "\n",
    "    pattern = re.compile(r'^(.*?)_(\\d+)_(\\d+)')\n",
    "\n",
    "    for filename in os.listdir(input_dir):\n",
    "        match = pattern.match(filename)\n",
    "        if match:\n",
    "            #class_name = match.group(1)\n",
    "            class_name = name_class\n",
    "            group_id = match.group(2)\n",
    "            weight_id = int(match.group(3))\n",
    "            image_groups[class_name].append((os.path.join(input_dir, filename), group_id, weight_id))\n",
    "\n",
    "    def load_image(image_path):\n",
    "        with Image.open(image_path) as img:\n",
    "            return np.array(img)\n",
    "\n",
    "    def get_next_data_folder(base_dir):\n",
    "        existing_folders = [d for d in os.listdir(base_dir) if d.startswith('data')]\n",
    "        if not existing_folders:\n",
    "            return os.path.join(base_dir, 'data1')\n",
    "        existing_numbers = [int(re.search(r'data(\\d+)', d).group(1)) for d in existing_folders if re.search(r'data(\\d+)', d)]\n",
    "        next_number = max(existing_numbers) + 1\n",
    "        return os.path.join(base_dir, f'data{next_number}')\n",
    "\n",
    "\n",
    "    for class_name, image_paths_groups_weights in image_groups.items():\n",
    "\n",
    "        class_dir = os.path.join(output_base_dir, class_name)\n",
    "        if not os.path.exists(class_dir):\n",
    "            os.makedirs(class_dir)\n",
    "\n",
    "\n",
    "        data_dir = get_next_data_folder(class_dir)\n",
    "        os.makedirs(data_dir, exist_ok=True)\n",
    "\n",
    "        group_images = defaultdict(list)\n",
    "        \n",
    "        for image_path, group_id, weight_id in image_paths_groups_weights:\n",
    "\n",
    "            image = load_image(image_path)\n",
    "\n",
    "\n",
    "            weight = weights.get(weight_id, 1) \n",
    "\n",
    "\n",
    "            group_images[group_id].append((image, weight))\n",
    "\n",
    "        for group_id, images_weights in group_images.items():\n",
    "\n",
    "            combined_image = np.zeros_like(images_weights[0][0], dtype=np.float64)\n",
    "            total_weight = 0\n",
    "\n",
    "            for image, weight in images_weights:\n",
    "                combined_image += image * weight\n",
    "                total_weight += weight\n",
    "\n",
    "            if total_weight > 0:\n",
    "                combined_image /= total_weight\n",
    "\n",
    "        \n",
    "            output_path = os.path.join(data_dir, f\"{group_id}.jpg\")\n",
    "            Image.fromarray(combined_image.astype(np.uint8)).save(output_path)\n",
    "\n",
    "            print(f\"image {output_path}  saved \")\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "import os\n",
    "\n",
    "def ran_all(all_video_input):\n",
    "    for video_path in os.listdir(all_video_input):\n",
    "        video_in_folder = os.path.join(all_video_input, video_path)\n",
    "\n",
    "        # 1: Delete files and folders\n",
    "        paths_delete_files = [ \n",
    "            video_folder,\n",
    "            convert_video_to_images_folder,\n",
    "            square_images_folder,\n",
    "            resized_images_folder,\n",
    "            detect_folder\n",
    "        ]\n",
    "\n",
    "        delete_files_and_folders(paths_delete_files)\n",
    "\n",
    "        # 2: Crop video\n",
    "        video_path_change_name_video = video_in_folder\n",
    "        save_path_change_name_video = video_in_video_folder\n",
    "\n",
    "        crop_video(video_path_change_name_video, save_path_change_name_video)\n",
    "\n",
    "        # 3: Run YOLOv5 detection\n",
    "        run_yolov5_detection(\n",
    "            video_source=video_in_video_folder,\n",
    "            weights_path=yolo_weights_path,\n",
    "            conf_threshold=0.4,\n",
    "            vid_stride=1\n",
    "        )\n",
    "\n",
    "        # 4: Convert video to images\n",
    "        video_path = video_in_video_folder\n",
    "        output_folder = convert_video_to_images_folder\n",
    "\n",
    "        convert_video_to_images(video_path, output_folder)\n",
    "\n",
    "        # 5: Convert photos to grayscale\n",
    "        input_folder = convert_video_to_images_folder\n",
    "\n",
    "        convert_photos_to_grayscale(input_folder)\n",
    "\n",
    "        # 6: Add number to the first file\n",
    "        folder_path_labels = labels_folder\n",
    "\n",
    "        add_number_to_ferst_file(folder_path_labels)\n",
    "\n",
    "        # 7: Prepare text file for cutting images\n",
    "        directory_path_labels_folder = labels_folder\n",
    "\n",
    "        Prepare_text_file_for_cut_image(directory_path_labels_folder)\n",
    "\n",
    "        # 8: Delete lines in files that haven't six numbers\n",
    "        Deleted_lines_in_files_that_haven_not_six_number(directory_path_labels_folder)\n",
    "\n",
    "        # 9: Delete file and image\n",
    "        labels_directory = labels_folder\n",
    "        images_directory = convert_video_to_images_folder\n",
    "\n",
    "        Deleted_file_and_image(labels_directory, images_directory)\n",
    "\n",
    "        # 10: Cut image by text file\n",
    "        labels_folder_path = labels_folder\n",
    "        images_folder_path = convert_video_to_images_folder\n",
    "        save_folder = square_images_folder\n",
    "\n",
    "        cut_image_by_text_file(labels_folder_path, images_folder_path, save_folder)\n",
    "\n",
    "        # 11: Resize images\n",
    "        input_folder_square_images_Dimensions = square_images_folder\n",
    "        output_folder_resized_images_Dimensions = resized_images_folder\n",
    "        size = (128, 128)\n",
    "\n",
    "        resize_images(input_folder_square_images_Dimensions, output_folder_resized_images_Dimensions, size)\n",
    "\n",
    "        # 12: Mix image with LDA\n",
    "        input_dir = resized_images_folder\n",
    "        output_base_dir = dataset_end\n",
    "        weights = {\n",
    "            1: 0.5,\n",
    "            2: 0.5,  \n",
    "            3: 0.5   \n",
    "        }\n",
    "\n",
    "        mix_image_with_LDA(input_dir, output_base_dir, weights)\n",
    "\n",
    "\n",
    "########### ran \n",
    "ran_all(all_video_input)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
